# Generated by Django 6.0.5 on 2026-05-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
