# Generated by Django 6.0.5 on 2026-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
    migrations.AddField(
        model_name='userprofile',
        name='bio',
        field=models.TextField(blank=True),
    ),
    migrations.AlterField(
        model_name='userprofile',
        name='experience',
        field=models.IntegerField(default=0),
    ),
]