# Generated by Django 6.0.5 on 2026-06-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_about_remove_userprofile_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='specialization',
        ),
    ]
