# Generated by Django 6.0.5 on 2026-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_remove_product_quantity_product_farmer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable')], default='fruit', max_length=20),
            preserve_default=False,
        ),
    ]
